### ISSUE TITLE
build errors in kmscube, weston etc

### ISSUE THREAD

**Issue by pushkar90** [NVIDIA/tegra-nouveau-rootfs#24]
86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/5.2.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lEGL
/aarch64-linux-gnu/bin/ld: cannot find -lGLESv2
etc

Can you tell me where I'm going wrong? Afaik it pulls the needed files from git, but maybe there's a problem with symbolic links?

**Comment by Gnurou** [comment]
Could you post a more complete log of your build attempt on pastebin and post the link here?

**Comment by pushkar90** [comment]
Went to bed. But I managed to solve the EGL related issues while building weston.
The tegra-nouveau-rootfs directory had a bunch of broken links. So I found the appropriate files it's supposed to link to and added them in.

Now I get this error? after running build-xserver. Xserver and libinput succesfully installed, I just don't understand what it's trying to do right after that or if it's important at all.

http://pastebin.com/gLun0iwA

**Comment by Gnurou** [comment]
I think at this stage the best thing to do would be to wipe out the out/ directory, re-run "repo sync -c", and run the scripts again from the beginning. You're probably not doing anything wrong but maybe you built a newer version on top of an older one and that caused these issues.

Please let me know if you are still having these issues on a fresh build.

**Comment by zeroepoch** [comment]
May be related to realpath issues I created a ticket for since it creates some broken symlinks.  I never ran into this issue starting from scratch today with coreutils updated to the version of vivid.

**Comment by Gnurou** [comment]
Very likely. I have commited a fix to #27 , so closing this issue.
