### ISSUE TITLE
Missing Ubuntu dependency libxml2-dev

### ISSUE THREAD

**Issue by zeroepoch** [NVIDIA/tegra-nouveau-rootfs#32]
I started again from scratch and `libxml2-dev` is now needed to build pkg-config during the `download-gcc` step.

**Comment by zeroepoch** [comment]
I noticed also pkg-config is extracted at $TOP rather than somewhere in `out`.  I don't know if that was intentional or not.

**Comment by Gnurou** [comment]
Added, thanks! pkg-config extracted on $TOP is expected since that's where we keep all sources.
