### ISSUE TITLE
Bad freedesktop path in manifest file l4t-nouveau.xml

### ISSUE THREAD

**Issue by eleaver** [NVIDIA/tegra-nouveau-rootfs#5]
fetch="git://anongit.freedesktop.org/" -> fetch="git://anongit.freedesktop.org/git/"

(someone may have changed the path after you posted the manifest file.)

**Comment by eleaver** [comment]
Hmm... should be fetch="http://anongit.freedesktop.org/git/"

**Comment by Gnurou** [comment]
Thanks, that should be fixed now. Strange, I would swear the old URL was working too.
