### ISSUE TITLE
./scripts/build-drm issue

### ISSUE THREAD

**Issue by gallit** [NVIDIA/tegra-nouveau-rootfs#9]
I'm having an issue when i try to run that script.

Error is:
checking for VALGRIND... no
checking whether to enable Valgrind support... configure: error: Valgrind support required but not present

I installed the valgrind package but no success.
Can someone tell me witch package to install ?

valgrind installed version : valgrind-3.10.0.SVN
lsb_release : Ubuntu 14.04.3 LTS

**Comment by Gnurou** [comment]
Oops, this was a problem with the build script. I have fixed it - please run "repo sync -c" again and then you will be able to keep building from ./scripts/build-drm (make sure to set the TOP variable again!)
